import PDFDocument from "pdfkit";
import { NextResponse } from "next/server";

export const runtime = "nodejs";

export async function GET() {
  const doc = new PDFDocument({ size: "A4", margin: 50 });

  // Basic, deterministic resume content (replace/extend as needed).
  doc.font("Helvetica-Bold").fontSize(20).text("Dhananjaya R B", {
    align: "left",
  });
  doc.moveDown(0.5);
  doc
    .font("Helvetica")
    .fontSize(11)
    .fillColor("#111827")
    .text("Tech Lead • Bangalore, India", { continued: false });
  doc
    .font("Helvetica")
    .fontSize(11)
    .fillColor("#374151")
    .text("DOB: 01-11-1992");
  doc
    .font("Helvetica")
    .fontSize(11)
    .fillColor("#374151")
    .text("Email: dhananjayarb98@gmail.com");
  doc
    .font("Helvetica")
    .fontSize(11)
    .fillColor("#374151")
    .text("Mobile: 9071361273 / 8105294450");
  doc
    .font("Helvetica")
    .fontSize(11)
    .fillColor("#374151")
    .text("LinkedIn: linkedin.com/in/dhananjaya-rb-a64890122");
  doc
    .font("Helvetica")
    .fontSize(11)
    .fillColor("#374151")
    .text("GitHub: github.com/DhananjayaRB");

  doc.moveDown(1);
  doc.font("Helvetica-Bold").fontSize(13).fillColor("#111827").text("Summary");
  doc.moveDown(0.25);
  doc
    .font("Helvetica")
    .fontSize(11)
    .fillColor("#374151")
    .text(
      "Tech Lead with 10+ years of experience designing and building enterprise-grade mobile, web, and cloud applications. Expertise in Xamarin, Flutter, Laravel, ASP.NET, Azure Cloud, and AI-integrated solutions. Proven track record delivering Payroll, Attendance, CRM, and Enterprise SaaS platforms end-to-end.",
      { width: 500 }
    );

  doc.moveDown(0.75);
  doc.font("Helvetica-Bold").fontSize(13).fillColor("#111827").text("Core Skills");
  doc.moveDown(0.25);
  doc
    .font("Helvetica")
    .fontSize(11)
    .fillColor("#374151")
    .text(
      "Mobile: Xamarin, Xamarin Forms, Flutter\nBackend: Laravel, ASP.NET, ASP.NET Core, Microservices\nCloud/DevOps: Azure (VM/Functions/App Services/Kubernetes), Azure DevOps, Jenkins, CI/CD\nIntegrations: SMS, WhatsApp APIs, KYC, Tally/Zoho/DarwinBox, RabbitMQ/Service Bus\nAI: LLMs, agent-style workflows",
      { width: 500 }
    );

  doc.moveDown(0.75);
  doc.font("Helvetica-Bold").fontSize(13).fillColor("#111827").text("Key Work");
  doc.moveDown(0.25);
  doc
    .font("Helvetica")
    .fontSize(11)
    .fillColor("#374151")
    .text(
      "- Payroll, Attendance, Leave, Expense, CRM (Enterprise + NGO)\n- EziiSign document builder with e-signing features (Form 16, DSC Sign)\n- Integrations: Tally, Zoho, DarwinBox, KYC, SMS/WhatsApp\n- Azure architecture and cost optimization\n- CI/CD pipelines and containerized deployments",
      { width: 500 }
    );

  doc.moveDown(0.75);
  doc
    .font("Helvetica")
    .fontSize(10)
    .fillColor("#6b7280")
    .text("Generated by portfolio site • Replace with your official resume when ready.");

  const pdfBuffer = await new Promise<Buffer>((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    doc.end();
  });

  const pdfBytes = new Uint8Array(pdfBuffer);

  return new NextResponse(pdfBytes, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": 'attachment; filename="resume.pdf"',
      "Cache-Control": "no-store",
    },
  });
}

